server:
  port: 8000
spring:
  profiles:
    active: dev
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true
  thymeleaf:
    cache: false
  #messages: i18n.login
# debug: true # 开启 spring boot debug模式

---
server:
     port: 8080
spring:
  profiles: dev
---
server:
     port: 8082
spring:
  profiles: prod